settings:
  name: BlueXP workload factory
  platform: cloud
  search: workload-setup-admin,workload-fsx-ontap,workload-databases,workload-vmware,workload-genai,workload-relnotes
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: true
    lipi_enabled: true
sidebar: 
  entries:
  - title: All workload factory documentation
    url: /index.html