settings:
  name: NetApp Workload Factory
  search: workload-setup-admin,workload-fsx-ontap,workload-databases,workload-vmware,workload-genai,workload-builders,workload-eda, workload-relnotes
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: true
    lipi_enabled: true
sidebar: 
  entries:
  - title: All Workload Factory documentation
    url: /index.html