== Tools to use NetApp Workload Factory
You can use NetApp Workload Factory with the following tools:

* *Workload Factory console*: The Workload Factory console provides a visual, holistic view of your applications and projects.
* *NetApp Console*: The NetApp Console provides a hybrid interface experience so that you can use Workload Factory along with other NetApp data services.
* *Ask me*: Use the Ask me AI assistant to ask questions and learn more about Workload Factory without leaving the Workload Factory console. Access Ask me from the Workload Factory help menu.
* *CloudShell CLI*: Workload Factory includes a CloudShell CLI to manage and operate AWS and NetApp environments across accounts from a single, browser-based CLI. Access CloudShell from the top bar of the Workload Factory console.
* *REST API*: Use the Workload Factory REST APIs to deploy and manage your FSx for ONTAP file systems and other AWS resources.
* *CloudFormation*: Use AWS CloudFormation code to perform the actions you defined in the Workload Factory console to model, provision, and manage AWS and third-party resources from the CloudFormation stack in your AWS account.
* *Terraform NetApp Workload Factory provider*: Use Terraform to build and manage infrastructure workflows generated in the Workload Factory console.
